name: Terraform Jobs Template
on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: 'Setup Google Cloud Auth ğŸ”'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Google Cloud SDK ğŸ”§'
        uses: 'google-github-actions/setup-gcloud@v1'

      - uses: hashicorp/setup-terraform@v1
      
      - name: Plan ğŸ“„
        run: |
          cd ${{ inputs.workspace }}
          terraform plan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: 'Setup Google Cloud Auth ğŸ”'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Google Cloud SDK ğŸ”§'
        uses: 'google-github-actions/setup-gcloud@v1'

      - uses: hashicorp/setup-terraform@v1
      
      - name: Apply ğŸ› ï¸
        run: |
          cd ${{ inputs.workspace }}
          terraform apply
