name: Terraform Jobs Template
on: []
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: 'Setup Google Cloud Auth ğŸ”'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Google Cloud SDK ğŸ”§'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Terraform Plan ğŸ”'
        uses: hashicorp/terraform-plan@v1
        with:
          working-directory: .
          plan: true

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: 'Setup Google Cloud Auth ğŸ”'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Google Cloud SDK ğŸ”§'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Terraform Apply ğŸ› ï¸'
        uses: hashicorp/terraform-apply@v1
        with:
          working-directory: .
          apply: true
