name: Terraform Jobs Template
on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: 'Setup Google Cloud Auth ğŸ”'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Setup Google Cloud SDK ğŸ”§
        uses: google-github-actions/setup-gcloud@v1
  
      - name: Setup Terraform ğŸ”§
        uses: hashicorp/setup-terraform@v1
      
      - name: Plan ğŸ“„
        env:
          PLAN_FILE: plan.tfplan
        run: |
          export WORKSPACE_ID=$(echo ${{ inputs.workspace }} | sed "s/\//-/g")
          echo "PLAN_FILE=$PLAN_FILE" >> $GITHUB_ENV
          echo "WORKSPACE_ID=$WORKSPACE_ID" >> $GITHUB_ENV
          cat $GITHUB_ENV
          cd ${{ inputs.workspace }}
          terraform init
          terraform plan -out $PLAN_FILE
          sha1sum $PLAN_FILE

      - name: Upload Plan ğŸ’¾
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ID }}-terraform-plan
          retention-days: 3
          path: ${{ inputs.workspace }}/plan.tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Google Cloud Auth ğŸ”
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Setup Google Cloud SDK ğŸ”§
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup Terraform ğŸ”§
        uses: hashicorp/setup-terraform@v1

      - name: Download Plan ğŸ›ï¸
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ID }}-terraform-plan
          path: ${{ inputs.workspace }}
      
      - name: Apply ğŸ› ï¸
        env:
          PLAN_FILE: plan.tfplan
        run: |
          cd ${{ inputs.workspace }}
          sha1sum $PLAN_FILE
          terraform apply $PLAN_FILE
